### ISSUE TITLE
Add neutron network

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-crawler#149]
- bank
- core
- auth
- authz
- distribution
- gov
- mint
- slashing
- feegrant
- ibc
- liquidity
- ics
- cosmwasm a
- admin-module (https://github.com/neutron-org/admin-module)
- everything from here: https://github.com/neutron-org/neutron/tree/main/x
- block-sdk (https://github.com/skip-mev/block-sdk)

and everything that have been missed and will be find after the first sync

**Comment by malekvictor** [comment]
resolved in [v1.1.0](https://github.com/bro-n-bro/spacebox-crawler/releases/tag/v1.1.0)
