### ISSUE TITLE
Add distribution_rewards table

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-crawler#15]
```sql=
height int
validator str
rewards COIN str?
```

index on height, validator

[hint](https://docs.cosmos.network/v0.47/modules/distribution#beginblocker)

**Comment by malekvictor** [comment]
Maybe use _amount_ name instead of _reward_? Because this is the name in the `begin_blocker` field

**Comment by bro-n-bro-0** [comment]
This table is empty
