### ISSUE TITLE
Refine GPRC limits 

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/spacebox-crawler#166]
`ResourceExhausted desc = grpc: received message larger than max (20406494 vs. 4194304)" cmp=worker height=5919810`
Error at crawler
https://stackoverflow.com/questions/55362342/grpc-received-message-larger-than-max-8653851-vs-4194304

**Comment by malekvictor** [comment]
use GRPC_MAX_RECEIVE_MESSAGE_SIZE_BYTES to increase max size of received message
