### ISSUE TITLE
Renaming fixes

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-crawler#90]
- [x] delegation_reward_message table. validator_address -> operator_address
- [x] distribution_commission table. validator -> operator_address (now is operator, but operator_address is correct. Please fix)
- [x] distribution_rewards table. validator -> operator_address (now is operator, but operator_address is correct. Please fix)
- [x] handle_validator_signature table. address -> operator_address
- [x] proposer_reward table. validator -> operator_address
- [x] unbonding_delegation table. validator_address -> operator_address, completition_timestamp -> completion_time
- [x] unbonding_delegation_message table. validator_address -> operator_address, completition_timestamp -> completion_time
- [x] unjail_message. validator_addr -> operator_address
- [x] validator_description table. Drop the avatar_url field
- [x] validator_status table. validator_address -> consensus_address
- [x] withdraw_validator_commission_message. validator_address -> operator_address

**Comment by evgen3000** [comment]
Hey friends! Could you please change coin attribute to coins in tables. And everywhere use an array for this attribute. This would make it easier to interact with your database
